# Base configuration for signal convolution experiments
# This file contains common settings that can be inherited

out_dir: ./outputs

# Default model architecture
model:
    family: gpt2
    n_embd: 256
    n_layer: 12
    n_head: 4
    n_positions: 101

# Default training settings
training:
    batch_size: 64
    learning_rate: 0.0001
    train_steps: 500000
    save_every_steps: 1000
    keep_every_steps: 100000
    num_training_examples: 10000
    loss_space: time

    # Default curriculum
    curriculum:
        points:
            start: 5
            end: 41
            inc: 1
            interval: 2000
        dims:
            start: 64
            end: 64
            inc: 0
            interval: 1

# Default wandb settings
wandb:
    project: signal-incontext
    entity: your-entity
    log_every_steps: 10
    notes: ""

test_run: false